// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEUQbUfYrzlvkyHxtvuB1hPBX0zEInLH8',
    appId: '1:613265399604:web:1c0d5f638b545ba3054f61',
    messagingSenderId: '613265399604',
    projectId: 'my-project-1544653009300',
    authDomain: 'my-project-1544653009300.firebaseapp.com',
    storageBucket: 'my-project-1544653009300.appspot.com',
    measurementId: 'G-JJL9R62KWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQtnTcANRoLqxmIs06wbElf9GRch4k9cE',
    appId: '1:613265399604:android:aa3fe167bf9d64bd054f61',
    messagingSenderId: '613265399604',
    projectId: 'my-project-1544653009300',
    storageBucket: 'my-project-1544653009300.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWYUJpkKtwMDh9b6MfLs30YdvQg6SFMMs',
    appId: '1:613265399604:ios:4146db39cf4e8d51054f61',
    messagingSenderId: '613265399604',
    projectId: 'my-project-1544653009300',
    storageBucket: 'my-project-1544653009300.appspot.com',
    iosClientId: '613265399604-7b21prps4adq4baegft1c1aqrn7jclul.apps.googleusercontent.com',
    iosBundleId: 'com.jectlabstudio.lindosorvete.lindosorveteclient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWYUJpkKtwMDh9b6MfLs30YdvQg6SFMMs',
    appId: '1:613265399604:ios:4146db39cf4e8d51054f61',
    messagingSenderId: '613265399604',
    projectId: 'my-project-1544653009300',
    storageBucket: 'my-project-1544653009300.appspot.com',
    iosClientId: '613265399604-7b21prps4adq4baegft1c1aqrn7jclul.apps.googleusercontent.com',
    iosBundleId: 'com.jectlabstudio.lindosorvete.lindosorveteclient',
  );
}
